### ISSUE TITLE
[Enhancement] Toggle player visibility per zone 

### ISSUE THREAD

**Issue by trowieuk** [SheepGoMeh/VisibilityPlugin#14] opened 2021-08-30 19:31 UTC
Could you add maybe a zone blacklist where you choose which zones you want the plugin to be enabled. I'd like players in limsa and other main cities to be invisible but not in low pop areas.

**Comment by SheepGoMeh** [comment] 2021-08-30 20:03
Duplicate of #7

**Comment by trowieuk** [comment] 2021-08-30 20:10
My bad, sorry!

**Closed** 2022-06-19 13:46 UTC
