### ISSUE TITLE
Voidlisted People Still Visible

### ISSUE THREAD

**Issue by jxmey** [SheepGoMeh/VisibilityPlugin#1] opened 2021-01-23 22:19 UTC
Hello!

So, I have an entire list of voidlisted folks that I went ahead and added manually because... I can't really stomach waiting to see them in game to do it, so I just typed all of the names in. Yet, I still saw some of them appear (and I've also refreshed to see if it'd fix this, but nothing).

Do they have to be in the same area/logged in in order for me to manually add them and them not show up again, or is there something else I'm missing?

Thank you!

**Comment by SheepGoMeh** [comment] 2021-01-24 14:08
Are they from other worlds or ones you met in a duty?

**Comment by jxmey** [comment] 2021-01-24 14:28
They're just people I've known from my own home world.

**Comment by greenpills** [comment] 2021-02-26 13:15
> 
> 
> Are they from other worlds or ones you met in a duty?

Would you mind explaining why did you ask this? I was going to open a new issue, but if voiding players from other worlds not working as intended is a known issue, it might be the reason the problems I'm facing.

**Comment by SheepGoMeh** [comment] 2021-04-15 10:38
> They're just people I've known from my own home world.
> […](#)
> On Jan 24, 2021, at 9:08 AM, SheepGoMeh ***@***.***> wrote: ﻿ Are they from other worlds or ones you met in a duty? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Is this still an issue, or has it been resolved with the recent version?

**Closed** 2021-04-15 16:34 UTC
Labels: bug, needs testing
